### ISSUE TITLE
Is this plugin still active?

### ISSUE THREAD

**Issue by patryyyck** [BitBagCommerce/SyliusProductBundlePlugin#3]
Hello,

Is this plugin still active?
If not, do you know an alternative Sylius plugin to manage sets of products?

Thanks

**Comment by macintoshplus** [comment]
Ping @patrick477

**Comment by oallain** [comment]
Looks like no :disappointed:

**Comment by czechmarcin** [comment]
@patryyyck the plugin should be working. We have merged one blocking PR today. If there are any problems with using this, ping us on slack 😄

**Comment by damonsson** [comment]
Still active, v 1.0.0 released, enjoy! :smile:
