### ISSUE TITLE
Doctrine conflict

### ISSUE THREAD

**Issue by kmonmousseau** [BitBagCommerce/SyliusProductBundlePlugin#33]
Hello guys,

I want to install this package, but am unable to do so with the latest version because of this part added to `composer.json` : 
```json
"conflict": {
    "doctrine/orm": "^2.10.0"
},
```
I currently have version `2.11.1` of `doctrine/orm` installed and I want to avoid the downgrade to `2.9`.

Any way to know why this package conflicts with `doctrine/orm:^2.10.0` ?

**Comment by pbalcerzak** [comment]
Fixed in #32
