### ISSUE TITLE
AddProductBundleToCartCommand serialization config not compatible with constructor fields

### ISSUE THREAD

**Issue by andersbjorkland** [BitBagCommerce/SyliusProductBundlePlugin#43]
**Affected SyliusProductBundlePlugin version**: v2.2.0
***Sylius version***: v1.12.5
***PHP version***: 8.0.23

## Describe the issue
When using the API-route `[PATCH] /api/v2/shop/product-bundles/{id}/add-to-cart` with the following body (as stipulated by `AddProductBundleToCartCommand`):  
```json
{
    "orderId": 1,
    "productCode": "example-bundle",
    "quantity": 1
}
```

I get the following response:  
`400 Bad Request`
```json
{
    "code": 400,
    "message": "Cannot create an instance of \"BitBag\\SyliusProductBundlePlugin\\Command\\AddProductBundleToCartCommand\" from serialized data because its constructor requires parameter \"orderId\" to be present."
}
```

The serialization file [AddProductBundleToCartCommand.xml](https://github.com/BitBagCommerce/SyliusProductBundlePlugin/blob/v2.2.0/src/Resources/config/serialization/AddProductBundleToCartCommand.xml) specifies two fields to be deserialized: `orderToken` and `quantity`. But the [AddProductBundleToCartCommand](https://github.com/BitBagCommerce/SyliusProductBundlePlugin/blob/v2.2.0/src/Command/AddProductBundleToCartCommand.php) requires `orderId`, `productCode`, and `quantity`. 

## Observation
While the serialization file is wrong, it proposes a better way to define the command-object. Since the route already contains an ID for the product-bundle, the `productCode` field is not necessary. `orderToken` is also a better way to associate the add of a bundle to a cart as that follows the convention of Sylius checkout API. 

## Possible solutions
1. Reconfigure the serialization so the fields `orderId`, `productCode`, and `quantity` is associated with the group `'shop:product_bundle:add_to_cart'`
2. Redefine the command-file and how it is used

**Comment by senghe** [comment]
The fix has been merged a while ago, so I'm kindly closing the issue :vulcan_salute:
