### ISSUE TITLE
Entity ProductBundleOrderItem mapping is invalid

### ISSUE THREAD

**Issue by joenilson** [BitBagCommerce/SyliusProductBundlePlugin#6]
I'm trying to install the CMSPlugin and i get an doctrine error, making a bin/console doctrine:schema:validate i get the following error:

```
 [FAIL] The entity-class BitBag\SyliusProductBundlePlugin\Entity\ProductBundleOrderItem mapping is invalid:
 * The association BitBag\SyliusProductBundlePlugin\Entity\ProductBundleOrderItem#orderItem refers to the inverse side field App\Entity\Order\OrderItem#productBundleItems which does not exist.
```

I review the src\Entity\OrderItem class that have the extension and i see that the protected value is:

```
    /**
     * @var Collection|ProductBundleOrderItemInterface[]
     *
     * @OneToMany(
     *     targetEntity="BitBag\SyliusProductBundlePlugin\Entity\ProductBundleOrderItemInterface",
     *     mappedBy="orderItem",
     *     cascade={"ALL"}
     * )
     */
    protected $productBundleOrderItems;
```

I will do some tests, but it don't allowme to install other plugins.

**Comment by patrick477** [comment]
Why doesn't it allow you to install other plugins?

**Comment by joenilson** [comment]
trying to do the doctrine:migrations:diff i have an error about 

```
  The table with name 'MYSYLIUSDB.sylius_product' already exists.
```

after that i was looking for the root cause, i run the doctrine:schema:validate and get the error above showed.

After that i found a difference between the package installed in vendor/bitbag/product-bundle and the git repo, in the bundle in the Resources/config/doctrine there is a Product.orm.xml file that caused the error, this file isn't present in the repo.

I removed it, run again doctrine:migrations:diff 
it generated the file and can make the doctrine:migrations:migrate

But when i run the bin/console cache:clear it tell me:

```
No mapping file found named 'Product.orm.xml' for class 'BitBag\SyliusProductBundlePlugin\Entity\Product'.
```

And i must to put again this Product.orm.xml file in the route Resources/config/doctrine again, run the cache:clear and now it's working.

But as other issue pointed the install guide is required for a correct implementation

**Comment by patrick477** [comment]
@joenilson There should be no more problems installing in version 1.0.0 version. If you still have problems then reopen this issue.
