### ISSUE TITLE
Error on installation 

### ISSUE THREAD

**Issue by jmarcone** [BitBagCommerce/SyliusProductBundlePlugin#9]
When  I tried to install this plugin on a clean Sylius 1.7 installation and following the steps on the documentation I got the following error when 
`Unrecognized option "links" under "sylius_grid.grids.sylius_admin_product.actions.main.create". Available options are "enabled", "icon", "label", "options", "position", "type".`

Also, could someone assist me with the doctrine XML configuration?
- is it mandatory? 
- should I add those xmls? where?
- how does it work given that Sylius come preconfigured with annotations 

Also,  it would be very helpful that you  add the the missing file's name comment  on the top of the file snippets ( bundles.php, product & itemOrder entities & XMLs) 

Thanks!

**Comment by marcinwarzybok** [comment]
I have the same error following the instructions

**Comment by marcinwarzybok** [comment]
I had the same issue. Documentation is wrong.
You need to paste sylius_grid from vendor/bitbag/product-bundle-plugin/tests/Application/config/packages/_sylius.yaml
`sylius_grid:
    grids:
        sylius_admin_product:
            actions:
                main:
                    create:
                        type: links
                        label: sylius.ui.create
                        options:
                            class: primary
                            icon: plus
                            header:
                                icon: cube
                                label: sylius.ui.type
                            links:
                                simple:
                                    label: sylius.ui.simple_product
                                    icon: plus
                                    route: sylius_admin_product_create_simple
                                configurable:
                                    label: sylius.ui.configurable_product
                                    icon: plus
                                    route: sylius_admin_product_create
                                bundle:
                                    label: bitbag_sylius_product_bundle.ui.bundle
                                    icon: plus
                                    route: bitbag_product_bundle_admin_product_create_bundle`

**Comment by moussaclarke** [comment]
@marcinwarzybok Thank you, super helpful!

@jmarcone Yes it's mandatory - you can't add annotations to your app entities as far as I understand it as the properties are actually on the traits.

What I did was to add the following to `config/packages/doctrine.yaml`.

```yaml
            BitBagProductBundlePlugin:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/packages/BitBagProductBundlePlugin/doctrine'
                prefix: 'App\Entity'
                alias: BitBagProductBundlePlugin
```

Then create a folder `config/packages/BitBagProductBundlePlugin/doctrine` and in there add two files `Product.Product.orm.xml` and `Order.OrderItem.orm.xml` in which you can copy and paste the xml from the readme doc. You should then be able to run the migration diff.

Hope this helps!

**Comment by moussaclarke** [comment]
Update - while the above helps to get the migrations done, it doesn't actually seem to transfer through to the mappings when the app is running, which suggests there might be more to it to make xml and annotation mappings coexist. `bin/console doctrine:schema:validate` was giving me:

```
Mapping
-------

 [FAIL] The entity-class BitBag\SyliusProductBundlePlugin\Entity\ProductBundleOrderItem mapping is invalid:
 * The association BitBag\SyliusProductBundlePlugin\Entity\ProductBundleOrderItem#orderItem refers to the inverse side field App\Entity\Order\OrderItem#productBundleOrderItems which does not exist.


 [FAIL] The entity-class BitBag\SyliusProductBundlePlugin\Entity\ProductBundle mapping is invalid:
 * The association BitBag\SyliusProductBundlePlugin\Entity\ProductBundle#product refers to the inverse side field App\Entity\Product\Product#productBundle which does not exist.
```

Meaning it couldn't see the custom mapping - probably some error in that config (my guess is the key name is somehow important), or perhaps you just can't have both in the same context.

In the end I wound up just forking the plugin, and adding the equivalent annotations to the traits anyway.

in vendor/bitbag/product-bundle-plugin/src/Entity/ProductBundlesAwareTrait.php:

```php
   /**
     * @var ProductBundleInterface
     * @ORM\OneToOne(
     *     targetEntity="BitBag\SyliusProductBundlePlugin\Entity\ProductBundleInterface",
     *     mappedBy="product",
     *     cascade={"all"}
     * )
     **/
    protected $productBundle;
```

in vendor/bitbag/product-bundle-plugin/src/Entity/ProductBundleOrderItemsAwareTrait.php:

```php
    /**
     * @var ArrayCollection|ProductBundleOrderItemInterface[]
     *
     * @ORM\OneToMany(
     *     targetEntity="BitBag\SyliusProductBundlePlugin\Entity\ProductBundleOrderItemInterface",
     *     mappedBy="orderItem",
     *     cascade={"all"}
     * )
     */
    protected $productBundleOrderItems;
```
